import numpy as np

def corcplxw(z, fout):
    """Write complex matrix to binary file."""
    data = np.concatenate([np.real(z).ravel(order="F"), np.imag(z).ravel(order="F")])
    fout.write(data.astype(np.float32).tobytes())

def aud2cor(y: np.ndarray, 
            octave_shift: int=0, 
            frame_length: int=4, 
            sigmoid_factor: float=-2, 
            time_constant: int=0,
            tp_margin: float=0, # fullness of temporal margin
            sp_margin: float=0, # fullness of spectral margin
            bandpass: bool=1,
            rates: np.ndarray=None,
            scales: np.ndarray=None,
            fname: str=''): 
    """
    Cortical rate-scale representation (forward transform).

    :param y: The auditory spectrogram of shape [:math:`[N,M]`], where :math:`N=128` is the number of frequency channels and :math:`M=ceil(len(x) / frame_length)` is the number of time-frames.
    :type y: numpy.ndarray

    :param tp_margin: Fullness of the temporal margin; any real value in [0,1].
    :type tp_margin: float, optional, default=0

    :param sp_margin: Fullness of the spectral margin; any real value in [0,1].
    :type sp_margin: float, optional, default=0

    :param bandpass: Controls passband for filter generating functions `gen_corf` and `gen_cort`. If set to 1, only bandpass filters will
        be generated.
    :type bandpass: bool, optional, default=1

    :param rates: Rate vector, in Hz, used to define temporal filter behavior. Each value is a characteristic temporal 
        modulation frequency that one (temporal) filter in the bank is tuned to. Temporal filters are generated by `gen_cort`.
        If none is given, set to `2 ** np.linspace(np.log2(0.5), np.log2(128), 32)`
    :type rates: np.ndarray, optional, default=None

    :param scales: Scale vector, in cycles/octave, used to define spectral filter behavior. Each value is a spectral 
        modulation frequency that one (spectral) filter in the bank is tuned to. Spectral filters are generated by `gen_corf`.
        If none is given, set to `2 ** np.linspace(np.log2(1/5), np.log2(10), 32)`
    :type scales: np.ndarray, optional, default=None

    :param fname: Name of binary file to save to disk. If an empty string, the result will not be saved.
    :type fname: str, optional, default=''

    .. note:: If using the output of `wav2aud` you need to transpose the audiogram to get shape (channels, time points) rather than (time points, channels)

    :returns: `cr` - Cortical representation (numpy.ndarray), shape (num_scales, num_rates*2, N+2*dN, M+2*dM)
    """

    # TODO Data types check

    # Check margins are within allowed range
    if not (0 <= tp_margin <= 1):
        raise ValueError(f"tp_margin must be in [0, 1], got {tp_margin}")
    if not (0 <= sp_margin <= 1):
        raise ValueError(f"sp_margin must be in [0, 1], got {sp_margin}")

    # set default spfilt and tpfilt params
    if scales is None:
        scales = 2 ** np.linspace(np.log2(1/5), np.log2(10), 32)
    if rates is None:
        rates = 2 ** np.linspace(np.log2(0.5), np.log2(128), 32)

    scales = np.asarray(scales).ravel()
    rates = np.asarray(rates).ravel()
    num_rates = len(rates) # number of rate channels K1
    num_scales = len(scales) # number of scale channels K2
    N, M = y.shape # dimensions of audiogram; shape (timepoints, num channels)

    fps = 1000.0 / frame_length # frames per second (fps)
    ch_per_oct = 20 if M == 95 else 24 # channels per octave (ch_per_oct)

    # --- FFT padding sizes ---
    N_pad = int(2 ** np.ceil(np.log2(N)))
    #N2 = N_pad * 2
    M_pad = int(2 ** np.ceil(np.log2(M)))
    #M2 = M_pad * 2

    # --- 2D FFT of auditory spectrogram ---
    # First along frequency axis, then along time axis
    Y = np.zeros((N_pad*2, M_pad), dtype=complex)
    for n in range(N):
        R1 = np.fft.fft(y[n, :], 2*M_pad)
        Y[n, :] = R1[:M_pad]
    for m in range(M_pad): # !! fft on output of previous (Y)
        # NOTE Allows you to capture interaction
        R1 = np.fft.fft(Y[:N, m], 2*N_pad)
        Y[:, m] = R1

    # --- Index setup ---
    dM   = int(np.floor(M / 2 * sp_margin))

    # frequency margin indices into the (2*M_pad)-length IFFT output
    mdx1 = np.concatenate([
        np.arange((2*M_pad) - dM, (2*M_pad)), # wrap-around (left margin)
        np.arange(0, M + dM) # main + right margin
    ]).astype(int)

    dN   = int(np.floor(N / 2 * tp_margin))
    ndx  = np.arange(0, N + 2 * dN)   # time indices into IFFT output
    ndx1 = ndx

    # --- Output array ---
    cr = np.zeros((num_scales, num_rates * 2, N + 2 * dN, M + 2 * dM), dtype=complex)

    # --- Open output file ---
    write_file = len(fname) > 0
    if write_file:
        fout = open(fname, 'wb')
        header = np.array(
            [frame_length, time_constant, sigmoid_factor, octave_shift] + [num_scales, num_rates] + list(scales) + list(rates) + [N, M, tp_margin, sp_margin],
            dtype=np.float32
        )
        fout.write(header.tobytes())

    # ------------------------------------------------------------------ #
    # Main loop: rate × direction × scale                                #
    # ------------------------------------------------------------------ #
    for rdx in range(num_rates):
        cf_rt = rates[rdx] # PASS shape [idx, num_rates]
        HR = gen_cort(cf_rt, N_pad, fps, [rdx + 1 + bandpass, num_rates + bandpass * 2])

        for sgn in [1, -1]:

            if sgn > 0:
                HR = np.concatenate([HR, np.zeros(N_pad, dtype=complex)])

            else:
                HR = np.concatenate([HR[:1], np.conj(HR[1:2*N_pad][::-1])])
                HR[N_pad] = abs(HR[N_pad+1])

            # --- First IFFT (along time axis) pulled out of scale loop ---
            z1_freq = np.zeros((2*N_pad, M_pad), dtype=complex)
            for m in range(M_pad):
                z1_freq[:, m] = HR * Y[:, m] # equivalent to convolution (with frequency-domain wavelet) using convolution theorem
            z1 = np.fft.ifft(z1_freq, axis=0)   # (2*N_pad, M_pad) trying to match original freq and time to s.t. modulation patterns found
            z1 = z1[ndx1, :]                     # (N+2*dN, M_pad)

            for sdx in range(num_scales):
                cycles_per_oct = scales[sdx]
                HS = gen_corf(cycles_per_oct, M_pad, ch_per_oct, [sdx + 1 + bandpass, num_scales + bandpass * 2])

                # --- Second IFFT (along frequency axis) ---
                z = np.zeros((N + 2 * dN, M + 2 * dM), dtype=complex)
                for n in range(N + 2 * dN):
                    R1 = np.fft.ifft(z1[n, :] * HS.conj(), (2*M_pad))
                    z[n, :] = R1[mdx1]

                # Store in output array
                col = rdx + (num_rates if sgn == 1 else 0)
                cr[sdx, col, :, :] = z

                if write_file:
                    corcplxw(z, fout)
    if write_file:
        fout.close()


    return cr


# ------------------------------------------------------------------ #
# Filter generators — stubs matching the MATLAB originals             #
# ------------------------------------------------------------------ #

def gen_cort(cf: float, filt_len: int, sf: int, PASS: np.ndarray=None):
    """ 
    Calculates temporal filter transfer function in the frequency domain based on the given
    parameters.

    The time points t are built from a vector of indices from 0 to L-1, which are then
    divided by the sampling rate and multiplied by the characteristic frequency, which
    converts time to 'one period of the characteristic frequency'. This helps standardize
    the shape of the impulse response across different sampling rates.

    The shape of the temporal impulse response `h` is a gamma function as described in Chi(2005), which
    is then multiplied by `cf` to ensure similar behavior across different center frequencies.
    The result is adjusted to have zero-mean (remove zero-frequencies). 
    
    The Fourier transform of `h` is computed to convert this time-domain representation into the frequency domain, 
    which is useful for computationally efficient convolution/filtering. The output `H0` contains both positive 
    and negative frequencies, but only the positive frequencies are taken here. This allows us to build a filter that is 
    sensitive to modulation direction: the filter responds only to positive modulation frequencies, 
    and after conjugation, it responds only to negative modulation frequencies.

    The amplitude and phase information are stored separately, the ampltiude is normalized by the maximum and then
    the lowpass, highpass or bandpass characteristics are implemented, depending on the value of `PASS`. For a 
    lowpass filter, everything up to the maximum of H is flattened to 1 (ideal pass). Likewise, 
    for highpass behavior, everything from the maximum of H until the end is flattened to 1. If bandpass behavior
    is specified, H remains unchanged. The amplitude and phase are then used to construct the transfer function
    (complex-valued frequency response) for the filter, given by `H * np.exp(1j*A)`

    :param cf: Characteristic frequency, in Hz
    :type cf: float

    :param filt_len: Length of the filter, ideally a power of 2 for computational efficiency
    :type filt_len: int

    :param sf: Sampling frequency, in Hz
    :type sf: int

    :param PASS: Array of shape `[idx, upper_bound]` where `idx` denotes index and `upper_bound` is the maximum 
        value of this index. Dictates passband. 
        If none supplied, defaults to bandpass. Possible values and outcomes:
            - `idx = 1`: lowpass
            - `1 < idx < upper_bound` or `None`: bandpass
            - `idx = upper_bound`: highpass
    :type PASS: np.ndarray

    :returns: numpy.ndarray - Complex-valued filter transfer function (in frequency domain)
    """
    t = np.arange(filt_len) / sf * cf

    #gamma func as defined in Chi(2005)
    time_resp = np.sin(2*np.pi*t) * t**2 * np.exp(-3.5*t) * cf 

    # make sure response is zero-mean
    time_resp = time_resp - np.mean(time_resp)

    # convert to frequency domain, get phase and amplitude
    freq_resp = np.fft.fft(time_resp, 2*filt_len) 

    phase = np.angle(freq_resp[:filt_len])
    amplitude = np.abs(freq_resp[:filt_len])

    # normalize amplitude
    max_idx = np.argmax(amplitude)
    amplitude /= amplitude[max_idx]

    # change amplitude if necessary according to passband requirements
    if PASS is not None:
        if PASS[0] == 1: # lowpass
            amplitude[:max_idx] = 1
        elif PASS[0] == PASS[1]: # highpass
            amplitude[max_idx+1:] = 1

    return amplitude * np.exp(1j*phase)


def gen_corf(cycles_per_oct, filt_len, ch_per_oct, KIND=2):
    """ 
    Calculates frequency-domain transfer function for a spectral filter based on
    the given parameters.

    A scale (`octave_offsets`) is calculated: the relative position along the filter length
    is mapped to a frequency axis of one octave, then divided by two to span half an octave 
    instead. The higher the number of channels per octave, the higher your number of 'steps'
    (units) and hence the higher the frequency resolution. This scale is divided by the
    number of cycles per octave, producing units of 'channels per 0.5 cycles'.

    Two functions can be used to define the filter response, either a Gabor function or the
    negative second derivative of a Gaussian. Importantly, it is their frequency-domain forms
    that are used.

    For a lowpass filter, everything up to the maximum is flattened to 1 (ideal pass). Likewise, 
    for highpass filtering, everything from the maximum until the end is flattened to 1. In both
    cases, the sum of the transfer function is readjusted to preserve the filter's gain across all
    passbands. If bandpass behavior is specified, the transfer function remains unchanged. 

    :param cycles_per_oct: (Spectral) modulation rate in cycles per octave
    :type cycles_per_oct: int

    :param filter_len: Filter length, ideally a power of 2
    :type filter_len: int

    :param ch_per_oct: Frequency resolution in channels per octave
    :type ch_per_oct: int

    :returns: np.ndarray - Filter transfer function (in frequency domain)
    """
    # TODO - Update docstring once the bottom todo is finished
    # TODO - Add causal/non causal explanation
    # TODO - Change function design to make this KIND/PASS thing less awkward
    if np.isscalar(KIND):
        PASS = [2,3]
    else:
        PASS = KIND
        KIND = 2

    octave_offsets = np.arange(filt_len)/filt_len * ch_per_oct/2/abs(cycles_per_oct)

    if KIND == 1:
        C1 = 1/(2*.3*.3)
        freq_tf = np.exp(-C1*(octave_offsets-1)**2) + np.exp(-C1*(octave_offsets+1)**2)
    else:
        octave_offsets = octave_offsets**2
        freq_tf = octave_offsets*np.exp(1-octave_offsets)

    if PASS[0] == 1:
        max_idx = np.argmax(freq_tf)
        s = np.sum(freq_tf)
        freq_tf[:max_idx] = 1
        freq_tf = freq_tf/np.sum(freq_tf)*s

    elif PASS[0] == PASS[1]:
        max_idx = np.argmax(freq_tf)
        s = np.sum(freq_tf)
        freq_tf[max_idx+1:] = 1
        freq_tf = freq_tf/np.sum(freq_tf)*s

    return freq_tf