import numpy as np

def corcplxw(z, fout):
    """Write complex matrix to binary file."""
    data = np.concatenate([np.real(z).ravel(order="F"), np.imag(z).ravel(order="F")])
    fout.write(data.astype(np.float32).tobytes())

def aud2cor(audiogram: np.ndarray, 
            frame_length: int=4,
            temporal_margin: float=0, # fullness of temporal margin
            spectral_margin: float=0, # fullness of spectral margin
            bandpass: int=1,
            rates: np.ndarray=None,
            scales: np.ndarray=None,
            channels_per_oct: int=None): 
    """
    Cortical rate-scale representation (forward transform).

    :param audiogram: The auditory spectrogram, i.e. the output of ``wav2aud``, of shape :math:`[N, M]`, where :math:`N` is the number of time-frames and :math:`M=128` is the number of frequency channels. Pass it in directly, exactly as returned by ``wav2aud`` (no transpose), matching the MATLAB NSL toolbox convention.
    :type audiogram: numpy.ndarray

    :param temporal_margin: Fullness of the temporal margin; any real value in [0,1].
    :type temporal_margin: float, optional, default=0

    :param spectral_margin: Fullness of the spectral margin; any real value in [0,1].
    :type spectral_margin: float, optional, default=0

    :param bandpass: Controls passband for filter generating functions `gen_corf` and `gen_cort`. If set to 1, only bandpass filters will
        be generated. Must be an integer boolean, i.e. the literal int `0` or `1`. Python's `True`/`False` are not
        accepted, since `bandpass` is used directly in arithmetic when building the `PASS` argument passed to
        `gen_corf` and `gen_cort`.
    :type bandpass: int, optional, default=1

    :param rates: Rate vector, in Hz, used to define temporal filter behavior. Each value is a characteristic temporal 
        modulation frequency that one (temporal) filter in the bank is tuned to. Temporal filters are generated by `gen_cort`.
        If none is given, set to `2 ** np.linspace(np.log2(0.5), np.log2(128), 32)`
    :type rates: np.ndarray, optional, default=None

    :param scales: Scale vector, in cycles/octave, used to define spectral filter behavior. Each value is a spectral 
        modulation frequency that one (spectral) filter in the bank is tuned to. Spectral filters are generated by `gen_corf`.
        If none is given, set to `2 ** np.linspace(np.log2(1/5), np.log2(10), 32)`
    :type scales: np.ndarray, optional, default=None

    :param channels_per_oct: Frequency resolution of the auditory spectrogram, in channels per octave. This determines
        how `gen_corf` interprets the spectral (frequency) axis of `audiogram` when generating filters. If you are using
        the default filters supplied by Shamma et al. (i.e. the ones loaded by `wav2aud` when no custom `filters`
        dictionary is given), leave this as `None` and it will default to `20 if M == 95 else 24`, matching the
        channel spacing of those filters. If you are using your own custom filters (e.g. a different number of
        channels per octave), you should supply the corresponding `channels_per_oct` value here explicitly, since it
        will not necessarily match the default.
    :type channels_per_oct: int, optional, default=None

    .. note:: The output of ``wav2aud`` already has shape :math:`[N, M]` = (time-frames, frequency channels) and is passed to ``aud2cor`` directly, with no transpose. This mirrors the MATLAB NSL toolbox, where ``aud2cor`` takes the ``wav2aud`` output as-is.

    :returns: `corticogram` - Cortical representation (numpy.ndarray), a 4-D complex array of shape
        (num_scales, num_rates*2, N + 2*dN, M + 2*dM), i.e. (scale, rate*2, time, frequency).
        The rate axis holds both sweep directions (hence num_rates*2), and the time/frequency axes
        include any margins added via ``temporal_margin`` / ``spectral_margin``. This matches the MATLAB NSL
        toolbox output ordering [scale, rate*2, time, frequency].
    """

    # --- Input validation ---

    assert isinstance(audiogram, np.ndarray) and audiogram.ndim == 2, "Input auditory spectrogram audiogram should be a 2-D numpy array."

    assert isinstance(frame_length, int) and frame_length > 0, "The frame_length parameter should be a positive integer."

    # Ensure temporal_margin and spectral_margin are floats or integers within [0, 1]
    assert isinstance(temporal_margin, (int, float)), "The temporal_margin parameter should be a float or integer."
    assert isinstance(spectral_margin, (int, float)), "The spectral_margin parameter should be a float or integer."

    # Ensure bandpass is an integer boolean: must be a numeric type (not bool) and equal to 0 or 1
    assert isinstance(bandpass, int) and not isinstance(bandpass, bool) and bandpass in (0, 1), \
        "The bandpass parameter should be an integer boolean, i.e. the int 0 or the int 1 (True/False are not accepted)."

    # Ensure rates, if supplied, is array-like
    if rates is not None:
        assert isinstance(rates, np.ndarray), "The rates parameter should be a numpy.ndarray, if supplied."

    # Ensure scales, if supplied, is array-like
    if scales is not None:
        assert isinstance(scales, np.ndarray), "The scales parameter should be a numpy.ndarray, if supplied."

    # Ensure channels_per_oct, if supplied, is a positive integer
    if channels_per_oct is not None:
        assert isinstance(channels_per_oct, int) and channels_per_oct > 0, "The channels_per_oct parameter should be a positive integer, if supplied."

    # Check margins are within allowed range
    if not (0 <= temporal_margin <= 1):
        raise ValueError(f"temporal_margin must be in [0, 1], got {temporal_margin}")
    if not (0 <= spectral_margin <= 1):
        raise ValueError(f"spectral_margin must be in [0, 1], got {spectral_margin}")

    # set default rate and scales params
    if scales is None:
        scales = 2 ** np.linspace(np.log2(1/5), np.log2(10), 32)
    if rates is None:
        rates = 2 ** np.linspace(np.log2(0.5), np.log2(128), 32)

    scales = np.asarray(scales).ravel()
    rates = np.asarray(rates).ravel()
    num_rates = len(rates) # number of rate channels K1
    num_scales = len(scales) # number of scale channels K2
    N, M = audiogram.shape # dimensions of audiogram; shape (timepoints, num channels)

    fps = 1000.0 / frame_length # frames per second (fps)
    if channels_per_oct is None:
        channels_per_oct = 20 if M == 95 else 24 # channels per octave (channels_per_oct)

    # --- FFT padding sizes ---
    N_pad = int(2 ** np.ceil(np.log2(N)))
    #N2 = N_pad * 2
    M_pad = int(2 ** np.ceil(np.log2(M)))
    #M2 = M_pad * 2

    # --- 2D FFT of auditory spectrogram ---
    # First along frequency axis, then along time axis
    Y = np.zeros((N_pad*2, M_pad), dtype=complex)
    for n in range(N):
        R1 = np.fft.fft(audiogram[n, :], 2*M_pad)
        Y[n, :] = R1[:M_pad]
    for m in range(M_pad): # !! fft on output of previous (Y)
        # NOTE Allows you to capture interaction
        R1 = np.fft.fft(Y[:N, m], 2*N_pad)
        Y[:, m] = R1

    # --- Index setup ---
    dM   = int(np.floor(M / 2 * spectral_margin))

    # frequency margin indices into the (2*M_pad)-length IFFT output
    mdx1 = np.concatenate([
        np.arange((2*M_pad) - dM, (2*M_pad)), # wrap-around (left margin)
        np.arange(0, M + dM) # main + right margin
    ]).astype(int)

    dN   = int(np.floor(N / 2 * temporal_margin))
    ndx  = np.arange(0, N + 2 * dN)   # time indices into IFFT output
    ndx1 = ndx

    # --- Output array ---
    corticogram = np.zeros((num_scales, num_rates * 2, N + 2 * dN, M + 2 * dM), dtype=complex)

    # ------------------------------------------------------------------ #
    # Main loop: rate × direction × scale                                #
    # ------------------------------------------------------------------ #
    for rdx in range(num_rates):
        tune_rate = rates[rdx] # PASS shape [idx, num_rates]
        HR = gen_cort(tune_rate, N_pad, fps, [rdx + 1 + bandpass, num_rates + bandpass * 2])

        for sgn in [1, -1]:

            if sgn > 0:
                HR = np.concatenate([HR, np.zeros(N_pad, dtype=complex)])

            else:
                HR = np.concatenate([HR[:1], np.conj(HR[1:2*N_pad][::-1])])
                HR[N_pad] = abs(HR[N_pad+1])

            # --- First IFFT (along time axis) pulled out of scale loop ---
            z1_freq = np.zeros((2*N_pad, M_pad), dtype=complex)
            for m in range(M_pad):
                z1_freq[:, m] = HR * Y[:, m] # equivalent to convolution (with frequency-domain wavelet) using convolution theorem
            z1 = np.fft.ifft(z1_freq, axis=0)   # (2*N_pad, M_pad)
            z1 = z1[ndx1, :] # (N+2*dN, M_pad)

            for sdx in range(num_scales):
                tune_scale = scales[sdx]
                HS = gen_corf(tune_scale, M_pad, channels_per_oct, PASS=[sdx + 1 + bandpass, num_scales + bandpass * 2])

                # --- Second IFFT (along frequency axis) ---
                z = np.zeros((N + 2 * dN, M + 2 * dM), dtype=complex)
                for n in range(N + 2 * dN):
                    R1 = np.fft.ifft(z1[n, :] * HS.conj(), (2*M_pad))
                    z[n, :] = R1[mdx1]

                # Store in output array
                col = rdx + (num_rates if sgn == 1 else 0)
                corticogram[sdx, col, :, :] = z



    return corticogram


# ------------------------------------------------------------------ #
# Filter generators — stubs matching the MATLAB originals             #
# ------------------------------------------------------------------ #

def gen_cort(cf: float, filt_len: int, sf: int, PASS: np.ndarray=None):
    """ 
    Calculates temporal filter transfer function in the frequency domain based on the given
    parameters.

    The time points t are built from a vector of indices from 0 to L-1, which are then
    divided by the sampling rate and multiplied by the characteristic frequency, which
    converts time to 'one period of the characteristic frequency'. This helps standardize
    the shape of the impulse response at different sampling rates.

    The shape of the temporal impulse response `h` is a gamma function as descorticogramibed in Chi(2005), which
    is then multiplied by `cf` to ensure similar behavior across different center frequencies.
    The result is adjusted to have zero-mean (remove zero-frequencies). 
    
    The Fourier transform of `h` is computed to convert this time-domain representation into the frequency domain, 
    which is useful for computationally efficient convolution/filtering. The output `H0` contains both positive 
    and negative frequencies, but only the positive frequencies are taken here. This allows us to build a filter that is 
    sensitive to modulation direction: the filter responds only to positive modulation frequencies, 
    and after conjugation, it responds only to negative modulation frequencies.

    The amplitude and phase information are stored separately, the ampltiude is normalized by the maximum and then
    the lowpass, highpass or bandpass characteristics are implemented, depending on the value of `PASS`. For a 
    lowpass filter, everything up to the maximum of H is flattened to 1 (ideal pass). Likewise, 
    for highpass behavior, everything from the maximum of H until the end is flattened to 1. If bandpass behavior
    is specified, H remains unchanged. The amplitude and phase are then used to construct the transfer function
    (complex-valued frequency response) for the filter, given by `H * np.exp(1j*A)`

    :param cf: Characteristic frequency, in Hz
    :type cf: float

    :param filt_len: Length of the filter, ideally a power of 2 for computational efficiency
    :type filt_len: int

    :param sf: Sampling frequency, in Hz
    :type sf: int

    :param PASS: Array of shape `[idx, upper_bound]` where `idx` denotes index and `upper_bound` is the maximum 
        value of this index. Dictates passband. 
        If none supplied, defaults to bandpass. Possible values and outcomes:
            - `idx = 1`: lowpass
            - `1 < idx < upper_bound` or `None`: bandpass
            - `idx = upper_bound`: highpass
    :type PASS: np.ndarray

    :returns: numpy.ndarray - Complex-valued filter transfer function (in frequency domain)
    """
    t = np.arange(filt_len) / sf * cf

    #gamma func as defined in Chi(2005)
    time_resp = np.sin(2*np.pi*t) * t**2 * np.exp(-3.5*t) * cf 

    # make sure response is zero-mean
    time_resp = time_resp - np.mean(time_resp)

    # convert to frequency domain, get phase and amplitude
    freq_resp = np.fft.fft(time_resp, 2*filt_len) 

    phase = np.angle(freq_resp[:filt_len])
    amplitude = np.abs(freq_resp[:filt_len])

    # normalize amplitude
    max_idx = np.argmax(amplitude)
    amplitude /= amplitude[max_idx]

    # change amplitude if necessary according to passband requirements
    if PASS is not None:
        if PASS[0] == 1: # lowpass
            amplitude[:max_idx] = 1
        elif PASS[0] == PASS[1]: # highpass
            amplitude[max_idx+1:] = 1

    return amplitude * np.exp(1j*phase)


def gen_corf(tune_scale: int, filt_len: int, channels_per_oct: int, PASS=None):
    """ 
    Calculates frequency-domain transfer function for a spectral filter based on
    the given parameters.

    A scale (`octave_offsets`) is calculated: the relative position along the filter length
    is mapped to a frequency axis of one octave, then divided by two to span half an octave 
    instead. The higher the number of channels per octave, the higher your number of 'steps'
    (units) and hence the higher the frequency resolution. This scale is divided by the
    number of cycles per octave, producing units of 'channels per 0.5 cycles'.

    Two functions can be used to define the filter response, either a Gabor function or the
    negative second derivative of a Gaussian, selected via `func_type`. Importantly, it is
    their frequency-domain forms that are used.

    For a lowpass filter, everything up to the maximum is flattened to 1 (ideal pass). Likewise, 
    for highpass filtering, everything from the maximum until the end is flattened to 1. In both
    cases, the sum of the transfer function is readjusted to preserve the filter's gain acorticogramoss all
    passbands. If bandpass behavior is specified, the transfer function remains unchanged. 

    :param tune_scale: (Spectral) modulation rate in cycles per octave
    :type tune_scale: int

    :param filt_len: Filter length, ideally a power of 2
    :type filt_len: int

    :param channels_per_oct: Frequency resolution in channels per octave
    :type channels_per_oct: int

    :param PASS: Array of shape `[idx, upper_bound]` where `idx` denotes index and `upper_bound` is the maximum
        value of this index. Dictates passband.
        If none supplied, defaults to bandpass (`[2, 3]`). Possible values and outcomes:
            - `idx = 1`: lowpass
            - `1 < idx < upper_bound`: bandpass
            - `idx = upper_bound`: highpass
    :type PASS: np.ndarray, optional, default=None

    :returns: np.ndarray - Filter transfer function (in frequency domain)

    .. note:: The original MATLAB implementation of this function included an option to use a Gabor (rather than a Gaussian)
        function to define filter behavior. Since it is unclear how modifying this parameter would affect the biological or 
        mathematical validity of the model, this option has been removed.
    """

    octave_offsets = np.arange(filt_len)/filt_len * channels_per_oct/2/abs(tune_scale)

    # Gaussian function used
    octave_offsets = octave_offsets**2
    freq_tf = octave_offsets*np.exp(1-octave_offsets)

    if PASS is not None:
        if PASS[0] == 1:
            max_idx = np.argmax(freq_tf)
            s = np.sum(freq_tf)
            freq_tf[:max_idx] = 1
            freq_tf = freq_tf/np.sum(freq_tf)*s

        elif PASS[0] == PASS[1]:
            max_idx = np.argmax(freq_tf)
            s = np.sum(freq_tf)
            freq_tf[max_idx+1:] = 1
            freq_tf = freq_tf/np.sum(freq_tf)*s

    return freq_tf